name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ci/cd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cocoapods-test:
    name: CocoaPods
    uses: SwiftyLab/ci/.github/workflows/cocoapods.yml@main
    strategy:
      matrix:
        platforms: ['macos', 'ios', 'tvos']
        # platforms: ['macos tvos', 'ios', 'watchos']
    with:
      platforms: ${{ matrix.platforms }}
